server:
  port: 8081
spring:
  application:
    name: IAM-Service
  datasource:
    url: jdbc:postgresql://localhost:5432/iam_db
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true

keycloak:
  auth-server-url: http://localhost:8181
  realm: wedding-planner
  resource: iam-service
  credentials:
    secret: YOUR_CLIENT_SECRET
  bearer-only: true
  ssl-required: none