server:
  port: 8081
spring:
  application:
    name: IAM-Service


keycloak:
  auth-server-url: http://localhost:8181
  realm: wedding-planner
  resource: iam-service
  credentials:
    secret: YOUR_CLIENT_SECRET
  bearer-only: true
  ssl-required: none